# Generated by Django 5.2.8 on 2025-11-18 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('type', models.CharField(choices=[('TEXT', 'Text Input'), ('SINGLE', 'Single Choice (one correct answer)'), ('MULTIPLE', 'Multiple Choice (several correct answers)')], default='SINGLE', max_length=10, verbose_name='Block Type')),
                ('question', models.TextField(verbose_name='Question')),
                ('subtext', models.TextField(blank=True, null=True, verbose_name='Task Description, Information')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Optional Image URL')),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='Optional Link URL')),
            ],
            options={
                'verbose_name': 'Block (Question)',
                'verbose_name_plural': 'Blocks (Questions)',
                'ordering': ['project', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='For text input questions, the correct answer goes here. Otherwise, it can be left empty.', verbose_name='Option Text')),
                ('is_correct', models.BooleanField(default=False, help_text='Check this if this is a correct answer/option.', verbose_name='Is Correct?')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='blueprints.block', verbose_name='Block')),
            ],
            options={
                'verbose_name': 'Answer (Option)',
                'verbose_name_plural': 'Answers (Options)',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Project Description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Date Deleted')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='block',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='blueprints.project', verbose_name='Project'),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('project', 'order')},
        ),
    ]
