# Generated by Django 5.2.8 on 2025-11-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(help_text='For text input questions, the correct answer goes here. Otherwise, it can be left empty.', max_length=500, verbose_name='Option Text'),
        ),
        migrations.AlterField(
            model_name='block',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Optional Image URL'),
        ),
        migrations.AlterField(
            model_name='block',
            name='link_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Optional Link URL'),
        ),
        migrations.AlterField(
            model_name='block',
            name='question',
            field=models.TextField(max_length=1000, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='block',
            name='subtext',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Task Description, Information'),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Project Name'),
        ),
    ]
