# Generated by Django 5.2.8 on 2025-11-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0003_alter_project_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='points',
            field=models.IntegerField(default=1, help_text='How many points is this answer worth? (Can be 0 or negative for penalties)', verbose_name='Points'),
        ),
    ]
