# Generated by Django 5.2.8 on 2026-01-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0004_answer_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['block', 'order'], 'verbose_name': 'Answer (Option)', 'verbose_name_plural': 'Answers (Options)'},
        ),
        migrations.RemoveField(
            model_name='block',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='gap_index',
            field=models.PositiveIntegerField(blank=True, help_text='Used for Gap Fill. Indicates which placeholder {1}, {2} this answer fills.', null=True, verbose_name='Gap Index'),
        ),
        migrations.AddField(
            model_name='answer',
            name='match_text',
            field=models.TextField(blank=True, help_text='Used for Matching type blocks.', max_length=500, null=True, verbose_name='Match Pair (Right Side)'),
        ),
        migrations.AddField(
            model_name='answer',
            name='numeric_value',
            field=models.FloatField(blank=True, help_text='Used for Range/Estimation questions.', null=True, verbose_name='Correct Numeric Value'),
        ),
        migrations.AddField(
            model_name='answer',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='The order of this answer in the block.', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='answer',
            name='tolerance',
            field=models.FloatField(blank=True, help_text='Used for Range/Estimation. How much deviation is allowed?', null=True, verbose_name='Tolerance (+/-)'),
        ),
        migrations.AddField(
            model_name='block',
            name='gap_text',
            field=models.TextField(blank=True, help_text='The task itself for Gap Fill blocks.', max_length=5000, null=True, verbose_name='Gap Text'),
        ),
        migrations.AddField(
            model_name='block',
            name='maintext',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Question or Value'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, help_text='For text input questions, the correct answer goes here. Otherwise, it can be left empty.', max_length=500, null=True, verbose_name='Option Text'),
        ),
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('text_input', 'Text Input'), ('single_choice', 'Single Choice (one correct answer)'), ('multiple_choice', 'Multiple Choice (several correct answers)'), ('matching', 'Matching'), ('ordering', 'Ordering'), ('sentence_ordering', 'Sentence Ordering'), ('gap_fill', 'Gap Fill'), ('range', 'Range'), ('text_static', 'Static Text'), ('divider', 'Divider')], default='single_choice', max_length=20, verbose_name='Block Type'),
        ),
    ]
