# Generated by Django 5.2.7 on 2025-11-11 18:02

import colorfield.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Group Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('invite_code', models.CharField(max_length=20, unique=True, verbose_name='Invite Code')),
                ('color', colorfield.fields.ColorField(default='#555555', image_field=None, max_length=25, samples=None, verbose_name='Group Color')),
                ('anticheat', models.BooleanField(default=False, verbose_name='Anti-cheat')),
                ('kiosk', models.BooleanField(default=False, verbose_name='Kiosk Mode')),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Date Deleted')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='GradePercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Grade Name')),
                ('min_percentage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Minimum Percentage')),
                ('max_percentage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Maximum Percentage')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_percentages', to='groups.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Grade Percentage',
                'verbose_name_plural': 'Grade Percentages',
                'ordering': ['group', '-max_percentage'],
                'unique_together': {('group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=10, verbose_name='Rank')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('date_left', models.DateTimeField(blank=True, null=True, verbose_name='Date Left')),
                ('left_reason', models.CharField(blank=True, choices=[('GROUP_DELETED', 'Group Deleted'), ('KICKED', 'Kicked by Admin'), ('LEFT', 'Left Voluntarily')], max_length=15, null=True, verbose_name='Left Reason')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Member',
                'verbose_name_plural': 'Group Members',
                'unique_together': {('user', 'group')},
            },
        ),
    ]
