# Generated by Django 5.2.8 on 2025-11-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='invite_code',
            field=models.CharField(max_length=8, unique=True, verbose_name='Invite Code'),
        ),
    ]
