# Generated by Django 5.2.7 on 2025-11-06 19:30

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupmember_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='color',
            field=colorfield.fields.ColorField(default='#555555', image_field=None, max_length=25, samples=None, verbose_name='Group Color'),
        ),
    ]
