# Generated by Django 5.2.7 on 2025-11-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradepercentage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='group',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Deleted'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='date_left',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Left'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='left_reason',
            field=models.CharField(blank=True, choices=[('KICKED', 'Kicked by Admin'), ('LEFT', 'Left Voluntarily')], max_length=10, null=True, verbose_name='Left Reason'),
        ),
    ]
