# Generated by Django 5.2.7 on 2025-11-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_gradepercentage_is_active_group_date_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='left_reason',
            field=models.CharField(blank=True, choices=[('GROUP_DELETED', 'Group Deleted'), ('KICKED', 'Kicked by Admin'), ('LEFT', 'Left Voluntarily')], max_length=15, null=True, verbose_name='Left Reason'),
        ),
    ]
