# Generated by Django 5.2.8 on 2025-11-26 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_grade'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='groups.grade', verbose_name='Associated Grade'),
        ),
        migrations.AddField(
            model_name='submittedanswer',
            name='points_awarded',
            field=models.IntegerField(default=0, help_text='The points the student earned for this specific answer.'),
        ),
    ]
