# Generated by Django 5.2.8 on 2026-02-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_submission_grade_submittedanswer_points_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Total Possible Points'),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Earned Points'),
        ),
    ]
