# Generated by Django 5.2.8 on 2026-03-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_submission_max_score_submission_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('TEST_START', 'Test Start'), ('TEST_FINISH', 'Test Finish'), ('STUDENT_CHEAT', 'Student Cheat')], default='TEST_START', max_length=20),
        ),
    ]
