# Generated by Django 5.2.8 on 2026-03-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_event_desc_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('TEST_START', 'Test Start'), ('TEST_FINISH', 'Test Finish'), ('STUDENT_CHEAT', 'Student Cheat'), ('TEACHER_BLOCK', 'Teacher Block'), ('TEACHER_CLOSE', 'Teacher Close')], default='TEST_START', max_length=20),
        ),
    ]
